spring:
  datasource:
    url: jdbc:sqlite:image.db
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
lolicon:
  api-key: ''
  cache: 10
  size1200: false
  auto-delete-download-image: false
  reuse-image: true
  confounding: true